/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as LayoutWiadomosciRouteImport } from './routes/_layout.wiadomosci'
import { Route as LayoutUstawieniaRouteImport } from './routes/_layout.ustawienia'
import { Route as LayoutOAplikacjiRouteImport } from './routes/_layout.o-aplikacji'
import { Route as LayoutKalendarzRouteImport } from './routes/_layout.kalendarz'
import { Route as LayoutPacjenciIndexRouteImport } from './routes/_layout.pacjenci.index'
import { Route as LayoutPacjenciIdRouteImport } from './routes/_layout.pacjenci.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWiadomosciRoute = LayoutWiadomosciRouteImport.update({
  id: '/wiadomosci',
  path: '/wiadomosci',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUstawieniaRoute = LayoutUstawieniaRouteImport.update({
  id: '/ustawienia',
  path: '/ustawienia',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOAplikacjiRoute = LayoutOAplikacjiRouteImport.update({
  id: '/o-aplikacji',
  path: '/o-aplikacji',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutKalendarzRoute = LayoutKalendarzRouteImport.update({
  id: '/kalendarz',
  path: '/kalendarz',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPacjenciIndexRoute = LayoutPacjenciIndexRouteImport.update({
  id: '/pacjenci/',
  path: '/pacjenci/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPacjenciIdRoute = LayoutPacjenciIdRouteImport.update({
  id: '/pacjenci/$id',
  path: '/pacjenci/$id',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/auth': typeof AuthRoute
  '/kalendarz': typeof LayoutKalendarzRoute
  '/o-aplikacji': typeof LayoutOAplikacjiRoute
  '/ustawienia': typeof LayoutUstawieniaRoute
  '/wiadomosci': typeof LayoutWiadomosciRoute
  '/pacjenci/$id': typeof LayoutPacjenciIdRoute
  '/pacjenci/': typeof LayoutPacjenciIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/kalendarz': typeof LayoutKalendarzRoute
  '/o-aplikacji': typeof LayoutOAplikacjiRoute
  '/ustawienia': typeof LayoutUstawieniaRoute
  '/wiadomosci': typeof LayoutWiadomosciRoute
  '/': typeof LayoutIndexRoute
  '/pacjenci/$id': typeof LayoutPacjenciIdRoute
  '/pacjenci': typeof LayoutPacjenciIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/auth': typeof AuthRoute
  '/_layout/kalendarz': typeof LayoutKalendarzRoute
  '/_layout/o-aplikacji': typeof LayoutOAplikacjiRoute
  '/_layout/ustawienia': typeof LayoutUstawieniaRoute
  '/_layout/wiadomosci': typeof LayoutWiadomosciRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/pacjenci/$id': typeof LayoutPacjenciIdRoute
  '/_layout/pacjenci/': typeof LayoutPacjenciIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/kalendarz'
    | '/o-aplikacji'
    | '/ustawienia'
    | '/wiadomosci'
    | '/pacjenci/$id'
    | '/pacjenci/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/kalendarz'
    | '/o-aplikacji'
    | '/ustawienia'
    | '/wiadomosci'
    | '/'
    | '/pacjenci/$id'
    | '/pacjenci'
  id:
    | '__root__'
    | '/_layout'
    | '/auth'
    | '/_layout/kalendarz'
    | '/_layout/o-aplikacji'
    | '/_layout/ustawienia'
    | '/_layout/wiadomosci'
    | '/_layout/'
    | '/_layout/pacjenci/$id'
    | '/_layout/pacjenci/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/wiadomosci': {
      id: '/_layout/wiadomosci'
      path: '/wiadomosci'
      fullPath: '/wiadomosci'
      preLoaderRoute: typeof LayoutWiadomosciRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/ustawienia': {
      id: '/_layout/ustawienia'
      path: '/ustawienia'
      fullPath: '/ustawienia'
      preLoaderRoute: typeof LayoutUstawieniaRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/o-aplikacji': {
      id: '/_layout/o-aplikacji'
      path: '/o-aplikacji'
      fullPath: '/o-aplikacji'
      preLoaderRoute: typeof LayoutOAplikacjiRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/kalendarz': {
      id: '/_layout/kalendarz'
      path: '/kalendarz'
      fullPath: '/kalendarz'
      preLoaderRoute: typeof LayoutKalendarzRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/pacjenci/': {
      id: '/_layout/pacjenci/'
      path: '/pacjenci'
      fullPath: '/pacjenci/'
      preLoaderRoute: typeof LayoutPacjenciIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/pacjenci/$id': {
      id: '/_layout/pacjenci/$id'
      path: '/pacjenci/$id'
      fullPath: '/pacjenci/$id'
      preLoaderRoute: typeof LayoutPacjenciIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutKalendarzRoute: typeof LayoutKalendarzRoute
  LayoutOAplikacjiRoute: typeof LayoutOAplikacjiRoute
  LayoutUstawieniaRoute: typeof LayoutUstawieniaRoute
  LayoutWiadomosciRoute: typeof LayoutWiadomosciRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutPacjenciIdRoute: typeof LayoutPacjenciIdRoute
  LayoutPacjenciIndexRoute: typeof LayoutPacjenciIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutKalendarzRoute: LayoutKalendarzRoute,
  LayoutOAplikacjiRoute: LayoutOAplikacjiRoute,
  LayoutUstawieniaRoute: LayoutUstawieniaRoute,
  LayoutWiadomosciRoute: LayoutWiadomosciRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutPacjenciIdRoute: LayoutPacjenciIdRoute,
  LayoutPacjenciIndexRoute: LayoutPacjenciIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
